In [51]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [52]:
print(type(a))

<class 'numpy.ndarray'>


In [53]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [54]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
b.ndim

3

In [56]:
a.ndim

1

In [57]:
print(a[4],a[0])

5 1


In [58]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
c[1,1:4]

array([7, 8, 9])

In [60]:
c[1,2]

8

In [61]:
b[0,1,0]

3

In [62]:
x=np.array([1,2,3,4],dtype='i')
x.dtype

dtype('int32')

In [63]:
a[1:5]

array([2, 3, 4, 5])

In [64]:
a[:2]

array([1, 2])

In [65]:
c.shape

(2, 5)

In [66]:
a.shape

(5,)

In [67]:
for i in c:
    for j in i:
        print(j)
    

1
2
3
4
5
6
7
8
9
10


In [68]:
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8


In [69]:
np.where(a==4)

(array([3], dtype=int64),)

In [70]:
f=np.array(['deeptha','aleena','hrudya','alaika'])
print(np.sort(f))

['alaika' 'aleena' 'deeptha' 'hrudya']


In [71]:
print(np.sort(b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
from numpy import random
random.randint(100,size=(3,5))


array([[96, 11,  2, 16, 96],
       [51, 57, 88, 34, 20],
       [59, 22, 90,  2,  4]])

In [73]:
random.choice([3,5,7,9],p=[0.1,0.3,0.4,0.2],size=(100))


array([9, 7, 7, 9, 3, 7, 9, 9, 9, 5, 9, 5, 3, 5, 7, 5, 7, 7, 9, 9, 5, 5,
       7, 5, 5, 7, 9, 9, 9, 7, 5, 7, 3, 9, 5, 5, 7, 9, 7, 9, 5, 9, 9, 5,
       7, 7, 3, 7, 7, 9, 5, 5, 9, 5, 3, 3, 7, 5, 7, 7, 7, 9, 7, 7, 3, 3,
       5, 5, 5, 9, 7, 9, 9, 3, 7, 5, 5, 7, 7, 3, 9, 9, 7, 9, 9, 7, 5, 7,
       5, 9, 5, 7, 3, 5, 3, 5, 9, 7, 5, 9])

In [74]:
import numpy as np
arr=np.arange(10)
np.save('saved_array',arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
load_array1 = np.load('saved_array.npy')
load_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr2=np.arange(25)
arr3=np.arange(5)
np.savez('saved_2array.npz',x=arr2,y=arr3)
load_2arr=np.load('saved_2array.npz')
print(load_2arr['x'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [77]:
y=np.searchsorted(a,10)
y

5

In [79]:
z=np.searchsorted(a,6,side = 'left')
z

5

In [49]:
a

array([1, 2, 3, 4, 5])