In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [3]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [4]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
b.ndim

3

In [6]:
a.ndim

1

In [7]:
print(a[4],a[0])

5 1


In [8]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
c[1,1:4]

array([7, 8, 9])

In [10]:
c[1,2]

8

In [11]:
b[0,1,0]

3

In [12]:
x=np.array([1,2,3,4],dtype='i')
x.dtype

dtype('int32')

In [13]:
a[1:5]

array([2, 3, 4, 5])

In [14]:
a[:2]

array([1, 2])

In [15]:
c.shape

(2, 5)

In [16]:
a.shape

(5,)

In [17]:
for i in c:
    for j in i:
        print(j)
    

1
2
3
4
5
6
7
8
9
10


In [18]:
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8


In [48]:
np.where(a==4)

(array([3], dtype=int64),)

In [25]:
f=np.array(['deeptha','aleena','hrudya','alaika'])
print(np.sort(f))

['alaika' 'aleena' 'deeptha' 'hrudya']


In [26]:
print(np.sort(b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
from numpy import random
random.randint(100,size=(3,5))


array([[40, 73, 44, 81, 93],
       [55, 62, 88,  3, 47],
       [10, 85, 28, 94, 18]])

In [42]:
random.choice([3,5,7,9],p=[0.1,0.3,0.4,0.2],size=(100))


array([7, 9, 9, 5, 7, 5, 7, 7, 9, 3, 5, 7, 5, 7, 7, 3, 5, 9, 9, 7, 5, 7,
       5, 3, 7, 7, 7, 7, 7, 7, 7, 7, 9, 3, 5, 7, 9, 5, 5, 9, 5, 7, 7, 3,
       7, 7, 5, 7, 7, 7, 7, 7, 9, 5, 5, 7, 9, 5, 5, 5, 7, 7, 5, 5, 7, 3,
       5, 7, 7, 7, 5, 5, 5, 9, 9, 7, 7, 5, 9, 5, 7, 7, 9, 5, 5, 7, 3, 5,
       9, 3, 3, 3, 7, 7, 7, 7, 5, 5, 7, 7])